# Generated by Django 2.0.6 on 2018-07-20 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [("person", "0001_initial"), ("party", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="Election",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("candidate_sequential", models.CharField(max_length=50)),
                ("legend_composition", models.CharField(max_length=250)),
                ("legend_name", models.CharField(max_length=250)),
                ("place", models.CharField(max_length=250)),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("1", "VEREADOR(A)"),
                            ("2", "VEREADOR(A) SUPLENTE"),
                            ("3", "VEREADOR(A) - INTERINO(A)"),
                            ("4", "VEREADOR(A) - CONSTITUINTE"),
                            ("5", "VEREADOR(A) - CONGRESSO REVISOR(A)"),
                            ("6", "PREFEITO(A) - INTERINO(A)"),
                            ("7", "PREFEITO(A)"),
                            ("8", "VICE-PREFEITO(A)"),
                            ("9", "VICE-PREFEITO(A) - CONSTITUINTE"),
                            ("10", "VICE-PREFEITO(A) - INTERINO(A)"),
                            ("11", "GOVERNADOR(A)"),
                            ("12", "GOVERNADOR(A) - INTERINO(A)"),
                            ("13", "VICE-GOVERNADOR(A)"),
                            ("14", "VICE-GOVERNADOR(A) - CONSTITUINTE"),
                            ("15", "DEPUTADO(A) FEDERAL"),
                            ("16", "DEPUTADO(A) FEDERAL - CONGRESSO REVISOR(A)"),
                            ("17", "DEPUTADO(A) FEDERAL - CONSTITUINTE"),
                            (
                                "18",
                                "DEPUTADO(A) FEDERAL - CONSTITUINTE E CONGRESSO REVISOR(A)",
                            ),
                            ("19", "DEPUTADO(A) ESTADUAL"),
                            ("20", "DEPUTADO(A) ESTADUAL - INTERINO"),
                            ("21", "DEPUTADO(A) ESTADUAL - CONSTITUINTE"),
                            ("22", "DEPUTADO(A) ESTADUAL - CONGRESSO REVISOR"),
                            ("23", "DEPUTADO(A) DISTRITAL"),
                            ("24", "DEPUTADO(A) DISTRITAL - CONSTITUINTE"),
                            ("25", "SENADOR(A)"),
                            ("26", "SENADOR(A) - CONGRESSO REVISOR(A)"),
                            ("27", "SENADORA(A) - CONSTITUINTE"),
                            ("28", "SENADOR(A) SUPLENTE"),
                            ("29", "PRESIDENTE(A) DA REPÚBLICA"),
                            ("30", "PRESIDENTE(A) DA REPÚBLICA - INTERINO(A)"),
                            ("31", "VICE-PRESIDENTE(A)"),
                            ("32", "2º SUPLENTE SENADOR(A)"),
                            ("33", "1º SUPLENTE SENADOR(A)"),
                            ("34", "1º SUPLENTE"),
                            ("35", "2º SUPLENTE"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("0 ", "NÃO INFORMADO"),
                            ("1", "ELEITO"),
                            ("2", "ELEITO POR QP"),
                            ("3", "SUPLENTE"),
                            ("4", "NÃO ELEITO"),
                            ("5", "2o TURNO"),
                            ("6", "REJEITADO"),
                            ("7", "SUBSTITUÍDO"),
                        ],
                        max_length=1,
                    ),
                ),
                ("state", models.CharField(max_length=250)),
                ("year", models.IntegerField()),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="person.Person"
                    ),
                ),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="party.Party"
                    ),
                ),
            ],
        )
    ]
