# Generated by Django 2.0.6 on 2018-07-20 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0001_initial'),
        ('party', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('position', models.CharField(max_length=250)),
                ('legend_name', models.CharField(max_length=250)),
                ('legend_composition', models.CharField(max_length=250)),
                ('result', models.CharField(max_length=250)),
                ('place', models.CharField(max_length=250)),
                ('state', models.CharField(max_length=250)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.Person')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='party.Party')),
            ],
        ),
    ]
