# Generated by Django 2.1 on 2018-08-13 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0005_avoid_charfields_with_null_values'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'verbose_name_plural': 'assets'},
        ),
        migrations.AlterModelOptions(
            name='donation',
            options={'verbose_name_plural': 'donations'},
        ),
        migrations.AlterModelOptions(
            name='election',
            options={'verbose_name_plural': 'elections'},
        ),
    ]
