# Generated by Django 2.1 on 2018-08-13 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("election", "0006_auto_20180813_2138")]

    operations = [
        migrations.AlterField(
            model_name="donation",
            name="description",
            field=models.CharField(blank=True, default="", max_length=250),
        )
    ]
