from collections import namedtuple


STATES = (
    ("AC", "Acre"),
    ("AL", "Alagoas"),
    ("AP", "Amapá"),
    ("AM", "Amazonas"),
    ("BA", "Bahia"),
    ("CE", "Ceará"),
    ("DF", "Distrito Federal"),
    ("ES", "Espírito Santo"),
    ("GO", "Goiás"),
    ("MA", "Maranhão"),
    ("MT", "Mato Grosso"),
    ("MS", "Mato Grosso do Sul"),
    ("MG", "Minas Gerais"),
    ("PA", "Pará"),
    ("PB", "Paraíba"),
    ("PR", "Paraná"),
    ("PE", "Pernambuco"),
    ("PI", "Piauí"),
    ("RJ", "Rio de Janeiro"),
    ("RN", "Rio Grande do Norte"),
    ("RS", "Rio Grande do Sul"),
    ("RO", "Rondônia"),
    ("RR", "Roraima"),
    ("SC", "Santa Catarina"),
    ("SP", "São Paulo"),
    ("SE", "Sergipe"),
    ("TO", "Tocantins"),
    ("ZZ", "Exterior"),
)

Term = namedtuple("Term", ("begins", "ends", "number"))
TERMS_BY_YEAR = {
    2015: Term(2015, 2019, 55),
    2011: Term(2011, 2015, 54),
    2007: Term(2007, 2011, 53),
    2003: Term(2003, 2007, 52),
    1999: Term(1999, 2003, 51),
    1995: Term(1995, 1999, 50),
    1991: Term(1991, 1995, 49),
    1987: Term(1987, 1991, 48),
}

POSITIONS = {
    "VEREADOR": "1",
    "VEREADORA": "1",
    "VEREADOR SUPLENTE": "2",
    "VEREADORA SUPLENTE": "2",
    "VEREADOR - INTERINO": "3",
    "VEREADORA - INTERINA": "3",
    "VEREADOR - CONSTITUINTE": "4",
    "VEREADORA - CONSTITUINTE": "4",
    "VEREADOR - CONGRESSO REVISOR": "5",
    "VEREADORA - CONGRESSO REVISOR": "5",
    "PREFEITO - INTERINO": "6",
    "PREFEITA - INTERINO": "6",
    "PREFEITO": "7",
    "PREFEITA": "7",
    "VICE-PREFEITO": "8",
    "VICE PREFEITO": "8",
    "VICE PREFEITA": "8",
    "VICE-PREFEITA": "8",
    "VICE-PREFEITO - CONSTITUINTE": "9",
    "VICE-PREFEITA - CONSTITUINTE": "9",
    "VICE-PREFEITO - INTERINO": "10",
    "VICE-PREFEITA - INTERINO": "10",
    "GOVERNADOR": "11",
    "GOVERNADORA": "11",
    "GOVERNADOR - INTERINO": "12",
    "GOVERNADORA - INTERINO": "12",
    "VICE-GOVERNADOR": "13",
    "VICE-GOVERNADORA": "13",
    "VICE-GOVERNADOR - CONSTITUINTE": "14",
    "VICE-GOVERNADORA - CONSTITUINTE": "14",
    "DEPUTADO FEDERAL": "15",
    "DEPUTADA FEDERAL": "15",
    "DEPUTADO FEDERAL (CONGRESSO REVISOR)": "16",
    "DEPUTADA FEDERAL (CONGRESSO REVISOR)": "16",
    "DEPUTADO FEDERAL (CONSTITUINTE)": "17",
    "DEPUTADA FEDERAL (CONSTITUINTE)": "17",
    "DEPUTADO FEDERAL (CONSTITUINTE) (CONGRESSO REVISOR)": "18",
    "DEPUTADO ESTADUAL": "19",
    "DEPUTADO ESTADUAL - INTERINO": "20",
    "DEPUTADO ESTADUAL - CONSTITUINTE": "21",
    "DEPUTADA ESTADUAL - CONSTITUINTE": "21",
    "DEPUTADO ESTADUAL - CONGRESSO REVISOR": "22",
    "DEPUTADA ESTADUAL - CONGRESSO REVISOR": "22",
    "DEPUTADO DISTRITAL": "23",
    "DEPUTADA DISTRITAL": "24",
    "DEPUTADO DISTRITAL - CONSTITUINTE": "24",
    "SENADOR": "25",
    "SENADORA": "25",
    "SENADOR - CONGRESSO REVISOR": "26",
    "SENADORA - CONGRESSO REVISOR": "26",
    "SENADOR - CONSTITUINTE": "27",
    "SENADORA - CONSTITUINTE": "27",
    "SENADOR SUPLENTE": "28",
    "PRESIDENTE": "29",
    "PRESIDENTE DA REPÚBLICA": "29",
    "PRESIDENTE DA REPÚBLICA - INTERINO": "30",
    "PRESIDENTA": "29",
    "PRESIDENTA DA REPÚBLICA": "29",
    "VICE-PRESIDENTE": "31",
    "2º SUPLENTE SENADOR": "32",
    "2º SUPLENTE SENADORA": "32",
    "1º SUPLENTE SENADOR": "33",
    "1º SUPLENTE SENADORA": "33",
    "1º SUPLENTE": "34",
    "2º SUPLENTE": "35",
}

ELECTION_RESULT = {
    "SUPLENTE": "3",
    "NÃO ELEITO": "4",
    "ELEITO POR QP": "2",
    "ELEITO": "1",
    "ELEITO POR MÉDIA": "1",
    "MÉDIA": "1",
    "REGISTRO NEGADO ANTES DA ELEIÇÃO": "6",
    "INDEFERIDO COM RECURSO": "6",
    "RENÚNCIA/FALECIMENTO/CASSAÇÃO ANTES DA ELEIÇÃO": "6",
    "2º TURNO": "5",
    "SUBSTITUÍDO": "7",
    "REGISTRO NEGADO APÓS A ELEIÇÃO": "6",
    "RENÚNCIA/FALECIMENTO COM SUBSTITUIÇÃO": "7",
    "RENÚNCIA/FALECIMENTO/CASSAÇÃO APÓS A ELEIÇÃO": "6",
    "CASSADO COM RECURSO": "6",
}


GENDER_CHOICES = (
    ("0", "NÃO INFORMADO"),
    ("1", "FEMININO"),
    ("2", "MASCULINO"),
    ("3", "OUTRO"),
)


GENDERS = {
    "FEMININO": "1",
    "FEM": "1",
    "F": "1",
    "MASCULINO": "2",
    "M": "2",
    "MASC": "2",
    "OUTRO": "3",
    "NÃO INFORMADO": 0,
}
