from perfil.party.models import Party
from perfil.utils.management.commands import ImportCsvCommand


class Command(ImportCsvCommand):

    help = "Import CSV generated by: https://brasil.io/dataset/eleicoes-brasil/candidatos"  # noqa
    model = Party
    bulk_size = 2 ** 13

    @staticmethod
    def group_names_by_initials(reader):
        grouped = {}
        for line in reader:
            initials, name = line['sigla_partido'], line['nome_partido']
            names = grouped.get(initials, [])
            names.append(name)
            grouped[initials] = names

        return grouped

    def serialize(self, reader):
        print('Cleaning the dataset…')
        data = self.group_names_by_initials(reader)

        print('Importing data…')
        for initials, names in data.items():
            *_, name = names  # last from the CSV is the most recent election
            yield Party(initials=initials, name=name)
