from tqdm import tqdm

from perfil.party.models import Party
from perfil.utils.management.commands import ImportCsvCommand


class Command(ImportCsvCommand):

    help = "Import CSV generated by: https://brasil.io/dataset/eleicoes-brasil/candidatos"  # noqa
    model = Party
    bulk_size = 2 ** 13
    slice_csv = False

    def group_names_by_initials(self, reader, total):
        grouped = {}
        original_desc = f'Importing {self.model.__name__} data'
        desc = 'Cleaning data'.ljust(len(original_desc), ' ')
        with tqdm(total=total, desc=desc, unit='lines') as progress_bar:
            for line in reader:
                initials, name = line['sigla_partido'], line['nome_partido']
                names = grouped.get(initials, [])
                names.append(name)
                grouped[initials] = names
                progress_bar.update(1)

        return grouped

    def serialize(self, reader, total, progress_bar):
        data = self.group_names_by_initials(reader, total)
        progress_bar.update(total - len(data))

        for initials, names in data.items():
            *_, name = names  # last from the CSV is the most recent election
            yield Party(initials=initials, name=name)
