# Generated by Django 2.0.7 on 2018-07-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_auto_20180725_1400'),
        ('mandate', '0002_auto_20180725_1400'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Politic',
            new_name='Politician',
        ),
        migrations.RemoveIndex(
            model_name='politician',
            name='mandate_pol_congres_f69287_idx',
        ),
        migrations.RemoveIndex(
            model_name='politician',
            name='mandate_pol_congres_d48e69_idx',
        ),
        migrations.AddIndex(
            model_name='politician',
            index=models.Index(fields=['congressperson_id'], name='mandate_pol_congres_195f1e_idx'),
        ),
        migrations.AddIndex(
            model_name='politician',
            index=models.Index(fields=['congressperson_name'], name='mandate_pol_congres_53eefd_idx'),
        ),
    ]
