# Generated by Django 2.1 on 2018-08-13 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mandate', '0003_auto_20180725_1401'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'activities'},
        ),
        migrations.AlterModelOptions(
            name='politician',
            options={'verbose_name_plural': 'politicians'},
        ),
        migrations.AlterModelOptions(
            name='term',
            options={'verbose_name_plural': 'terms'},
        ),
    ]
