# Generated by Django 2.1 on 2018-08-29 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandate', '0004_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='politician',
            name='area',
            field=models.CharField(choices=[('1', 'Câmara'), ('2', 'Senado')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='politician',
            name='congressperson_id',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterUniqueTogether(
            name='politician',
            unique_together={('congressperson_id', 'area')},
        ),
    ]
