# Generated by Django 2.1 on 2018-08-15 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0008_personinformation'),
        ('party', '0003_merge_20180806_1235'),
        ('mandate', '0004_auto_20180813_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyFiliation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='party.Party')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filiations', to='person.Person')),
            ],
        ),
        migrations.AlterField(
            model_name='politician',
            name='congressperson_id',
            field=models.CharField(max_length=250),
        ),
    ]
