# Generated by Django 2.1 on 2018-08-30 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("mandate", "0005_add_politician_area")]

    operations = [
        migrations.CreateModel(
            name="ClaimedIndemnification",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cnpj_cpf", models.CharField(max_length=14)),
                ("supplier", models.CharField(max_length=255)),
                ("claim_id", models.CharField(blank=True, default="", max_length=255)),
                ("month", models.IntegerField()),
                ("year", models.IntegerField()),
                ("category", models.CharField(blank=True, default="", max_length=255)),
                (
                    "sub_category",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("date", models.DateField(null=True)),
                ("value", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "politician",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mandate.Politician",
                    ),
                ),
            ],
            options={
                "verbose_name": "claimed indemnification",
                "verbose_name_plural": "claimed indemnifications",
            },
        ),
        migrations.AddIndex(
            model_name="claimedindemnification",
            index=models.Index(
                fields=["cnpj_cpf"], name="mandate_cla_cnpj_cp_464b5b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="claimedindemnification",
            index=models.Index(fields=["month"], name="mandate_cla_month_266647_idx"),
        ),
        migrations.AddIndex(
            model_name="claimedindemnification",
            index=models.Index(
                fields=["year", "month"], name="mandate_cla_year_bdf24f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="claimedindemnification",
            index=models.Index(fields=["date"], name="mandate_cla_date_e267ab_idx"),
        ),
    ]
