# Generated by Django 2.1 on 2018-08-30 19:05

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension, UnaccentExtension


class Migration(migrations.Migration):

    dependencies = [("mandate", "0006_create_claimed_indemnification_model")]

    operations = [TrigramExtension(), UnaccentExtension()]
