# Generated by Django 2.1 on 2018-08-27 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandate', '0006_lawproject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lawproject',
            name='authors',
        ),
        migrations.AlterField(
            model_name='politician',
            name='congressperson_id',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.DeleteModel(
            name='LawProject',
        ),
    ]
