# Generated by Django 2.0.7 on 2018-08-03 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_auto_20180725_1400'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name_plural': 'people'},
        ),
    ]
