# Generated by Django 2.0.7 on 2018-08-03 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0005_auto_20180802_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(blank=True, choices=[('0', 'NÃO INFORMADO'), ('1', 'FEMININO'), ('2', 'MASCULINO'), ('3', 'OUTRO')], max_length=1),
        ),
    ]
