# Generated by Django 2.0.7 on 2018-08-06 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0006_auto_20180803_1237"),
        ("person", "0005_auto_20180803_1425"),
    ]

    operations = []
