# Generated by Django 2.1 on 2018-08-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("person", "0008_personinformation")]

    operations = [
        migrations.AddField(
            model_name="personinformation",
            name="num_of_elections_won_by_quota",
            field=models.IntegerField(default=0),
            preserve_default=False,
        )
    ]
