# Generated by Django 2.1 on 2018-08-16 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("person", "0009_personinformation_num_of_elections_won_by_quota")]

    operations = [
        migrations.AddField(
            model_name="personinformation",
            name="civil_name",
            field=models.CharField(default="", max_length=250),
            preserve_default=False,
        )
    ]
