# Generated by Django 2.1 on 2018-08-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("person", "0010_personinformation_civil_name")]

    operations = [
        migrations.RenameField(
            model_name="personinformation",
            old_name="num_of_elections",
            new_name="election_parties_changed",
        ),
        migrations.RenameField(
            model_name="personinformation",
            old_name="num_of_elections_won",
            new_name="filiation_parties_changed",
        ),
        migrations.RenameField(
            model_name="personinformation",
            old_name="num_of_elections_won_by_quota",
            new_name="num_elections",
        ),
        migrations.AddField(
            model_name="personinformation",
            name="num_elections_won_by_quota",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="personinformation",
            name="total_elections_won",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
