# Generated by Django 2.1 on 2018-08-27 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("person", "0012_personinformation_elected_as_congressperson")]

    operations = [
        migrations.AlterModelOptions(
            name="person",
            options={"ordering": ["civil_name"], "verbose_name_plural": "people"},
        )
    ]
