from datetime import datetime
from textwrap import dedent

from django.core.cache import cache

from perfil.election.models import Donation, Election
from perfil.utils.management.commands import ImportCsvCommand


class Command(ImportCsvCommand):

    help = dedent("""
        Import CSV generated by: https://github.com/rafapolo/tribuna

        Organize data in a MySQL database as described in the instructions and
        then export a CSV with:

            SELECT *
            FROM doacoes
            WHERE tipo = "candidato"
            INTO OUTFILE '/path/to/some/dir/doacoes.csv'
            FIELDS TERMINATED BY ','
            ENCLOSED BY '"'
            LINES TERMINATED BY '\';

        You might have to add the following settings to your my.cnf:

            [mysqld]
            secure_file_priv=""

            [client]
            loose-local-infile=1
    """)

    model = Donation
    bulk_size = 2 ** 13

    @staticmethod
    def election_key(election):
        if isinstance(election, Election):
            keys = election.year, election.state, election.candidate_sequential
        else:
            keys = election['ano'], election['uf'], election['numero']

        key = '-'.join(keys)
        return f'election-{key}'

    def serialize(self, reader):
        print('Caching elections data…')
        for election in Election.objects.all().iterator():
            cache.set(self.election_key(election), election.id, 60 * 60 * 4)

        print('Import donations data…')
        for line in reader:
            election_id = cache.get(self.election_key(line))
            if election_id:
                yield Donation(
                    election_id=election_id,
                    donator=line['doador'],
                    donator_id=line['cpf_doador'],
                    original_donator=line['doador_original'],
                    original_donator_id=line['cpf_doador_original'],
                    date=datetime.strptime(line['data'], '%d/%m/%Y').date(),
                    value=line['valor'],
                    description=line['recurso']
                )
