# Generated by Django 2.0.6 on 2018-07-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initials', models.CharField(max_length=250, unique=True)),
                ('name', models.CharField(max_length=250)),
            ],
        ),
    ]
