# Generated by Django 2.0.7 on 2018-08-02 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("party", "0001_initial")]

    operations = [
        migrations.AlterModelOptions(
            name="party", options={"verbose_name_plural": "parties"}
        )
    ]
