# Generated by Django 2.0.7 on 2018-08-06 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("party", "0002_auto_20180802_2035"),
        ("party", "0002_auto_20180803_1425"),
    ]

    operations = []
