# Generated by Django 2.1.1 on 2018-09-09 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("core", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(decimal_places=2, max_digits=16, null=True),
                ),
                ("category", models.CharField(blank=True, default="", max_length=128)),
                ("category_code", models.IntegerField(null=True)),
                ("detail", models.CharField(blank=True, default="", max_length=255)),
                ("order", models.IntegerField(null=True)),
                ("last_update", models.DateTimeField(null=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.Candidate"
                    ),
                ),
            ],
            options={
                "verbose_name": "asset",
                "verbose_name_plural": "assets",
                "ordering": ("candidate__ballot_name", "-value"),
            },
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["candidate"], name="core_asset_candida_ebc618_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(fields=["value"], name="core_asset_value_85178c_idx"),
        ),
    ]
