# Generated by Django 2.1.1 on 2018-09-09 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0002_create_asset_model")]

    operations = [
        migrations.AddIndex(
            model_name="affiliation",
            index=models.Index(fields=["party"], name="core_affili_party_i_0be9c7_idx"),
        ),
        migrations.AddIndex(
            model_name="candidate",
            index=models.Index(
                fields=["politician"], name="core_candid_politic_eaff73_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="politician",
            index=models.Index(
                fields=["current_affiliation"], name="core_politi_current_0d8b0e_idx"
            ),
        ),
    ]
