# Generated by Django 2.1.1 on 2018-09-10 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0004_add_name_to_candidate_model")]

    operations = [
        migrations.AlterField(
            model_name="candidate", name="number", field=models.IntegerField(null=True)
        )
    ]
