# Generated by Django 2.1.1 on 2018-09-11 17:00

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("core", "0006_add_voter_id_to_candidate")]

    operations = [
        migrations.AddField(
            model_name="politician",
            name="asset_history",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        )
    ]
