# Generated by Django 2.1.1 on 2018-09-12 01:57

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("core", "0008_remove_m2m_affiliation_history")]

    operations = [
        migrations.AddField(
            model_name="politician",
            name="affiliation_history",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        )
    ]
