# Generated by Django 2.1.1 on 2018-09-12 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_add_affiliation_history_to_politician_as_json_field")
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="candidate", name="core_candid_state_6d2ad7_idx"
        ),
        migrations.RenameField(
            model_name="candidate", old_name="ethinicity", new_name="ethnicity"
        ),
        migrations.RenameField(
            model_name="candidate",
            old_name="ethinicity_code",
            new_name="ethnicity_code",
        ),
        migrations.AddIndex(
            model_name="candidate",
            index=models.Index(
                fields=["state", "post"], name="core_candid_state_812cc2_idx"
            ),
        ),
    ]
