# Generated by Django 2.1.1 on 2018-09-13 18:57

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_fix_typo_in_ethnicity_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='politician',
            name='election_history',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
    ]
