# Generated by Django 2.1.1 on 2018-09-18 17:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0012_add_indexes_based_on_candidate_list_view")]

    operations = [
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("summary", models.TextField(blank=True, default="")),
                ("name", models.CharField(blank=True, default="", max_length=16)),
                (
                    "keywords",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255), size=None
                    ),
                ),
                ("source_id", models.IntegerField()),
                ("url", models.URLField(unique=True)),
                (
                    "authors",
                    models.ManyToManyField(related_name="bills", to="core.Politician"),
                ),
            ],
            options={
                "verbose_name": "bill",
                "verbose_name_plural": "bills",
                "ordering": ("name",),
            },
        ),
        migrations.AddIndex(
            model_name="bill",
            index=models.Index(
                fields=["keywords"], name="core_bill_keyword_cb4141_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bill",
            index=models.Index(fields=["url"], name="core_bill_url_c45e78_idx"),
        ),
    ]
