# Generated by Django 2.1.1 on 2018-09-18 18:51

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("core", "0013_create_bill_model")]

    operations = [
        migrations.AddField(
            model_name="politician",
            name="bill_keywords",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        )
    ]
