# Generated by Django 2.1.1 on 2018-10-02 13:04

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("core", "0014_add_bill_keywords_to_politician")]

    operations = [
        migrations.AddField(
            model_name="politician",
            name="rosies_suspicions",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        )
    ]
