# Generated by Django 3.2.5 on 2021-10-26 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_fix_models_to_support_2021_datasets"),
    ]

    operations = [
        migrations.AlterField(
            model_name="affiliation",
            name="electoral_section",
            field=models.CharField(blank=True, default="", max_length=4),
        ),
    ]
