# Generated by Django 3.2.5 on 2021-11-11 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_alter_affiliation_electoral_section"),
    ]

    operations = [
        migrations.CreateModel(
            name="ElectionIncomeStatement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("value", models.DecimalField(decimal_places=2, max_digits=16)),
                (
                    "document_number",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "receipt_number",
                    models.CharField(blank=True, default="", max_length=75),
                ),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "accountant_sequential",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                (
                    "accountant_taxpayer_id",
                    models.CharField(blank=True, default="", max_length=11),
                ),
                (
                    "vice_candidate_taxpayer_id",
                    models.CharField(blank=True, default="", max_length=11),
                ),
                (
                    "deputy_substitute_taxpayer_id",
                    models.CharField(blank=True, default="", max_length=11),
                ),
                (
                    "donor_name",
                    models.CharField(blank=True, default="", max_length=256),
                ),
                (
                    "donor_taxpayer_id",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                (
                    "donor_economic_sector",
                    models.CharField(blank=True, default="", max_length=165),
                ),
                (
                    "donor_economic_sector_code",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                ("additional_information", models.JSONField(default=dict)),
            ],
            options={
                "verbose_name": "election income statement",
                "verbose_name_plural": "election income statements",
                "ordering": ("accountant_sequential", "year"),
            },
        ),
        migrations.AddIndex(
            model_name="electionincomestatement",
            index=models.Index(
                fields=["accountant_sequential"], name="core_electi_account_9ec3cd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="electionincomestatement",
            index=models.Index(
                fields=["accountant_taxpayer_id"], name="core_electi_account_9149e6_idx"
            ),
        ),
    ]
