# Generated by Django 3.2.5 on 2021-11-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_create_election_income_statement"),
    ]

    operations = [
        migrations.AddField(
            model_name="politician",
            name="electoral_income_history",
            field=models.JSONField(default=list),
        ),
    ]
