# Generated by Django 3.2.5 on 2022-06-29 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_add_candidate_owned_companies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliation',
            name='electoral_section',
            field=models.CharField(blank=True, default='', max_length=4, null=True),
        ),
    ]
