# Generated by Django 3.2.5 on 2022-09-19 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_city_code'),
    ]

    operations = [
        migrations.RunSQL("ALTER TABLE core_politician DROP COLUMN electoral_income_history")
    ]
